Repository aip-dev/google.aip.dev, pull requests merged in 2019-07, with the labels that each got.

#153 Fix 4222 query encoding
  aip/client-libraries/4222.md
Labels: cla: yes

#9 [AIP-133] Approve the AIP for the Create standard method.
  aip/0133.md
Labels: cla: yes

#159 Specify the right kind of RPC (copy/paste error)
  aip/0133.md
Labels: cla: yes

#157 [AIP-142] Time and duration
  aip/0142.md
Labels: cla: yes

#158 [feat] Add a banner over non-approved AIPs.
  _includes/aip-state-banner.html
  _layouts/default.html
  assets/js/global.js
Labels: cla: yes

#168 [fix] Fix typo in AIP-216.
  aip/0216.md
Labels: cla: yes

#169 [fix] Clarify page_token wording in AIP-132.
  aip/0132.md
Labels: cla: yes

#173 aip/213: bold "may" in existing common protos
  aip/0213.md
Labels: cla: yes

#164 [fix] Update the AIP-158 opacity requirement from should to must.
  aip/0158.md
Labels: aip: incorrect, cla: yes

#172 [AIP-141] Write AIP on quantities.
  aip/0141.md
Labels: cla: yes

#176 Correct typo.
  aip/adopting.md
Labels: cla: yes

#170 [AIP-216] Add explicit guidance on the unspecified value.
  aip/0216.md
Labels: cla: yes

#180 [fix] Address navbar spacing.
  _includes/aip-breadcrumb.html
  _layouts/default.html
  _sass/nav.scss
Labels: cla: yes

#178 Update 0142.md
  aip/0142.md
Labels: cla: yes

#171 [AIP-142] Approve the dates/times AIP.
  aip/0142.md
Labels: cla: yes

#185 Clarify the language on non-breaking changes in 0216.md
  aip/0216.md
Labels: cla: yes

#188 Fix #184 - Remove go-link
  aip/0100.md
Labels: aip: amendment, cla: yes

#187 Minor updates to AIP-140 draft
  aip/0140.md
Labels: cla: yes

#186 [AIP-140] Field names
  aip/0140.md
Labels: cla: yes

#190 Minor additions to AIP-141
  aip/0141.md
Labels: cla: yes

#189 [AIP-140] Approve the field names AIP.
  aip/0140.md
Labels: cla: yes

#156 [chore] Prettify some files.
  aip/0122.md
  aip/adopting.md
  aip/client-libraries/4221.md
  aip/client-libraries/4222.md
  aip/faq.md
  support/search.html
Labels: cla: yes

#196 may -> **should** for abbreviations
  aip/0141.md
Labels: cla: yes

#147 Adding draft AIPs for batch methods
  aip/0135.md
  aip/0231.md
  aip/0233.md
  aip/0234.md
  aip/0235.md
Labels: cla: yes

#181 [AIP-141] Approve the Quantities AIP.
  aip/0141.md
Labels: cla: yes

#191 [AIP-180] Backwards compatibility.
  aip/0122.md
  aip/0180.md
Labels: cla: yes

#194 [fix] Allow partial word match in search.
  support/search.html
Labels: cla: yes

#195 [AIP-143] Standardized codes
  aip/0143.md
Labels: cla: yes

#197 [AIP-154] Request validation
  aip/0154.md
Labels: cla: yes

#160 [AIP-123] Flesh out the annotation example slightly.
  aip/0123.md
Labels: cla: yes

#202 [chore] Prettify the batch AIPs.
  aip/0231.md
  aip/0233.md
  aip/0234.md
  aip/0235.md
Labels: cla: yes

#204 [AIP-151] Long-running operations
  aip/0151.md
Labels: cla: yes

#193 [AIP-126] Enumerations
  aip/0126.md
  aip/0216.md
Labels: cla: yes

#205 [AIP-192] Documentation
  aip/0192.md
Labels: cla: yes

#210 [AIP-193] Errors
  aip/0193.md
Labels: cla: yes

#215 minor edits for AIP-191
  aip/0191.md
Labels: cla: yes

#211 [AIP-159] Reading across collections
  aip/0159.md
Labels: cla: yes

#209 [AIP-191] File and directory structure
  aip/0191.md
Labels: cla: yes

#219 [AIP-122] Minor tweaks before approval
  aip/0122.md
Labels: cla: yes

#218 [AIP-1] Further clarify the quorum requirement.
  aip/0001.md
Labels: cla: yes

#221 Edits to AIP-134
  aip/0134.md
Labels: cla: yes

#222 Minor issues on AIP-193
  aip/0193.md
Labels: cla: yes

#224 [AIP-122] Changelog for previous PR
  aip/0122.md
Labels: cla: yes
