Repository aip-dev/google.aip.dev, pull requests merged in 2019-05, with the labels that each got.

#97 Add landing pages to AIP.dev
  README.md
  _config.yml
  _includes/aip-nav-mobile.html
  _includes/aip-nav.html
  _layouts/default.html
  _sass/aip/header.scss
  _sass/callouts.scss
  _sass/nav.scss
  aip/adopting.md
  aip/faq.md
  aip/general.md
  aip/index.md
  aip/licensing.md
  assets/css/style.scss
Labels: cla: yes, site: feature

#100 Fix #99 - Header bar was disappearing
  _sass/hercules.scss
Labels: cla: yes

#102 Add Google Analytics tag
  _layouts/default.html
Labels: cla: yes

#104 Fix #103 - Fixed broken redirect
  _config.yml
Labels: cla: yes

#106 Fix #105 - Made AIP area links absolute in mobile nav
  _includes/aip-nav-mobile.html
Labels: cla: yes

#107 Specify the type of error for a Cascading Delete
  aip/0135.md
Labels: cla: yes

#108 Fix fro => for typo
  aip/faq.md
Labels: cla: yes

#109 Approve the client libraries AIPs.
  aip/client-libraries/4210.md
  aip/client-libraries/4222.md
  aip/client-libraries/4231.md
  aip/client-libraries/4233.md
Labels: cla: yes

#92 [AIP-123] Resource types
  aip/0123.md
Labels: cla: yes

#95 [AIP-156] Singleton resources
  aip/0156.md
Labels: cla: yes

#94 [AIP-203] Clarify some details on required.
  aip/0203.md
Labels: aip: amendment, cla: yes

#113 Remove alias from Apps AIP page
  aip/apps/index.md
Labels: cla: yes

#115 [feat] Add GitHub logo.
  _layouts/default.html
  _sass/nav.scss
  assets/images/github.png
Labels: cla: yes

#114 [chore] Undo changes to Herclues, override the menubar transform.
  _sass/hercules.scss
  _sass/nav.scss
Labels: cla: yes

#116 [fix] Change permalink style to none.
  _config.yml
Labels: cla: yes

#118 [fix] Fix CSS.
  _config.yml
Labels: cla: yes

#119 Remove readme front matter
  README.md
  _config.yml
Labels: cla: yes

#121 Be more explicit about field type.
  aip/0122.md
Labels: cla: yes

#128 [AIP-4290] Docker interface
  aip/client-libraries/4290.md
Labels: cla: yes

#127 [feat] Print layout.
  _includes/aip-nav-mobile.html
  _layouts/default.html
  _sass/sidebar.scss
  assets/css/print.scss
Labels: cla: yes

#130 Remove errant CSS.
  _sass/sidebar.scss
Labels: cla: yes
