Repository aip-dev/google.aip.dev, pull requests merged in 2019-09, with the labels that each got.

#269 s/send/sent/ in AIP-158
  aip/0158.md
Labels: cla: yes

#268 Add missing RPC link to AIP-127
  aip/0127.md
Labels: cla: yes

#271 Fix typo: "parrent" to "parent".
  aip/0159.md
Labels: cla: yes

#263 Update 0217.md
  aip/0217.md
Labels: cla: yes

#259 [AIP-217] Unreachable resources
  aip/0159.md
  aip/0217.md
Labels: cla: yes

#274 [AIP-159] Fix typo.
  aip/0159.md
Labels: cla: yes

#217 [AIP-159] Approve the AIP for reading across collections
  aip/0159.md
Labels: cla: yes

#208 [AIP-151] Approve the long-running operations AIP.
  aip/0151.md
Labels: cla: yes

#214 [AIP-193] Approve the Errors AIP.
  aip/0193.md
Labels: cla: yes

#11 [AIP-134] Approve the AIP for Update.
  aip/0134.md
Labels: cla: yes

#198 [AIP-143] Approve the standardized codes AIP.
  aip/0143.md
Labels: cla: yes

#212 [AIP-126] Approve the enumerations AIP.
  aip/0126.md
Labels: cla: yes

#213 [AIP-192] Approve the Documentation AIP.
  aip/0192.md
Labels: cla: yes

#216 [AIP-191] Approve the file and directory structure AIP.
  aip/0191.md
Labels: cla: yes

#279 [AIP-205] Approve the beta blocking changes AIP.
  aip/0205.md
Labels: cla: yes

#276 [AIP-127] Approve the HTTP and gRPC Transcoding AIP.
  aip/0127.md
Labels: cla: yes

#275 [AIP-217] Approve the unreachable resources AIP.
  aip/0217.md
Labels: cla: yes

#287 Add the missing "to"
  aip/0133.md
Labels: cla: yes

#286 Add spacing beneath headers.
  _sass/headings.scss
Labels: cla: yes

#285 [AIP-141] Add prohibition on uint/fixed.
  aip/0141.md
Labels: cla: yes

#296 [AIP-210] Fix regex.
  aip/0210.md
Labels: cla: yes

#284 [AIP-9] Glossary
  aip/0009.md
Labels: cla: no

#294 [AIP-126] Correction.
  aip/0126.md
Labels: aip: incorrect, cla: yes

#295 [AIP-4231] Amend resource name parsing to include the file annotation.
  aip/client-libraries/4231.md
Labels: cla: yes

#301 Fix 'shortcut script' link in docker aip
  aip/client-libraries/4290.md
Labels: cla: yes

#303 [fix] Linkify RPCs
  aip/0127.md
Labels: cla: yes

#310 [AIP-151] Clarify fully-qualified names for imports.
  aip/0151.md
Labels: cla: yes

#311 [AIP-193] Add guidance about error message strings.
  aip/0193.md
Labels: cla: yes

#309 [AIP-127] Clarify request body encoding.
  aip/0127.md
Labels: cla: yes

#307 [AIP-154] Change the title.
  aip/0154.md
Labels: cla: yes

#308 [AIP-151] Add guidance on LRO errors.
  aip/0151.md
Labels: cla: yes

#314 [AIP-4232]: add restrictions on removal/alteration
  aip/client-libraries/4232.md
Labels: cla: yes
